// <auto-generated />
using System;
using JedoxifyMart.Services.StandsAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace JedoxifyMart.Services.StandsAPI.Migrations
{
    [DbContext(typeof(AppDBContext))]
    [Migration("20220222104940_Init2")]
    partial class Init2
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("JedoxifyMart.Services.StandsAPI.Models.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ProductId");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("JedoxifyMart.Services.StandsAPI.Models.Stand", b =>
                {
                    b.Property<int>("StandId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StandId"), 1L, 1);

                    b.Property<string>("StandName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("StandId");

                    b.ToTable("Stand");
                });

            modelBuilder.Entity("JedoxifyMart.Services.StandsAPI.Models.StandDetails", b =>
                {
                    b.Property<int>("StandDetailId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StandDetailId"), 1L, 1);

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int?>("StandId")
                        .HasColumnType("int");

                    b.HasKey("StandDetailId");

                    b.HasIndex("ProductId");

                    b.HasIndex("StandId");

                    b.ToTable("StandDetails");
                });

            modelBuilder.Entity("JedoxifyMart.Services.StandsAPI.Models.StandDetails", b =>
                {
                    b.HasOne("JedoxifyMart.Services.StandsAPI.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("JedoxifyMart.Services.StandsAPI.Models.Stand", null)
                        .WithMany("StandDetails")
                        .HasForeignKey("StandId");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("JedoxifyMart.Services.StandsAPI.Models.Stand", b =>
                {
                    b.Navigation("StandDetails");
                });
#pragma warning restore 612, 618
        }
    }
}
